export enum ErrorCodes {
	CITY_ALREADY_EXISTS = 'CITY_ALREADY_EXISTS',
	IMAGE_ALREADY_EXISTS = 'IMAGE_ALREADY_EXISTS',
	PLACE_ALREADY_EXISTS = 'PLACE_ALREADY_EXISTS',
	USER_ALREADY_EXISTS = 'USER_IS_ALREADY_EXISTS',
	DEFAULT_ERROR = 'DEFAULT_ERROR',
	WRONG_TOKEN = 'WRONG_TOKEN',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
	CITY_NOT_FOUND = 'PLACE_NOT_FOUND',
	USER_NOT_FOUND = 'USER_NOT_FOUND'
}
